### ISSUE TITLE
Border around addon/options pages still white.

### ISSUE THREAD

**Issue by Matakor** [NiklasGollenstede/stylish#10]
[Example](http://i.imgur.com/49nNphJ.png)
I tried editing it myself, but I couldn't figure it out. Still a style noob. =P

**Comment by NiklasGollenstede** [comment]
Unfortunately, that depends on the operating system, it's theme and the browsers theme.
On Windows 10 and Linux Mint, and I think every modern OS, it looks like this:

![image](https://cloud.githubusercontent.com/assets/10552031/23864452/dbf31d74-0812-11e7-8117-3b105e978667.png)

The sidebar is dark by default and there are no margins at the top/bottom.

Unfortunately (or not ...) I know nobody who still uses Windows 7 and don't have a VM at hand.

If I recall correctly I ran into this before and it was not trivial to fix. I may have a look at this later, but at the moment I don't have the time for it.

Or you could upgrade to a OS that was released this decade ....
(I think Microsoft still allows free upgrades, at least they did last November)

**Comment by Matakor** [comment]
That's bizarre, because I'm on windows 10.

**Comment by NiklasGollenstede** [comment]
Oh, Ok. As I said, the Os's and the Browsers theme (and Add-ons like Classic Theme Restorer) have an influence too.
Especially your buttons look like those of Windows 7. And of course the Firefox version matters too. If you are using ESR 45 or something, stuff is bound to look different.

Some more information would be helpful!

**Comment by Matakor** [comment]
Latest version of Firefox. I suppose it could be classic theme restorer (I tend to tinker a LOT).

EDIT:: Turns out it was CTR. Thanks for the assist, that was actually an easy fix. (CTR options, options tab, set back to default appearance, for posterity)

**Comment by NiklasGollenstede** [comment]
Glad I could help
