### ISSUE TITLE
close button, minimise...not visible 

### ISSUE THREAD

**Issue by dinamites** [NiklasGollenstede/stylish#13]
Hi.
just noticed this visual glitch on TT 53.
![buttons](https://cloud.githubusercontent.com/assets/27813039/25232307/19fdcb74-25db-11e7-8b3a-d93c1336ab19.jpg)

**Comment by NiklasGollenstede** [comment]
Jupp. Never really bothered me, though.
Anyway, this fixes that:

```
    /* tabs at the very top of the window */
    window[sizemode="normal"] #navigation-toolbox
    { margin-top: -17px; }
    window[sizemode="maximized"] #navigation-toolbox
    { margin-top: -2px; }

    /* exclude window button area */
    #titlebar-placeholder-on-TabsToolbar-for-captions-buttons
    { background: transparent; }
    window[sizemode="maximized"] #titlebar-placeholder-on-TabsToolbar-for-captions-buttons
    { background-image: linear-gradient(180deg, transparent 90%, black 90%); }
```

I want to test this some more before I release it. If you want to test it, paste the code above in a custom user style. Feel free to tell me what you think.

**Comment by dinamites** [comment]
works good! :)
