### ISSUE TITLE
Get Addons page in about:addons not darkened

### ISSUE THREAD

**Issue by Gitoffthelawn** [NiklasGollenstede/stylish#14]
The Get Addons page in about:addons is not darkened.  Is it possible to darken it too?

**Comment by NiklasGollenstede** [comment]
That page isn't really an `about:` page. It displays an embedded page from `https://discovery.addons.mozilla.org/`.
Therefore, it is explicitly excluded by "about:pages Dark". If you want it dark, you will need a separate style for that.
My "Mozilla.org Inverted" covers it.

**Comment by Gitoffthelawn** [comment]
Thank you sir!
