### ISSUE TITLE
Support for FF57 and beyond? (Some bugs w/ current CSS)

### ISSUE THREAD

**Issue by seascape** [NiklasGollenstede/stylish#16]
This is a really cool-looking theme.

I took your userstyles.org code and pasted it into FF58 Nightly's userContent.css (I think that is the only way to apply it right now?). It more or less worked but I think you would notice some irregularities. The add-on page sidebar is still white, for example.

The one thing that definitely made it unuseable was that add-on settings became complete invisible in the add-on manager (black on black, seemingly).

Anyway, it seems like it's 95% functional in new Firefox, so that's great.

**Comment by NiklasGollenstede** [comment]
I am sorry for the late reply. I only just noticed this issue, don't know how I could miss it. 
Anyway, I mostly fixed the FF57+ look the day after you asked (5dbf233e932f5618c1bf0522ff268d3ebf6e050a):
![image](https://user-images.githubusercontent.com/10552031/31608367-70b7c3d0-b270-11e7-816a-a94a22db02c8.png)

> pasted it into FF58 Nightly's userContent.css

Yes. It depends on which part of the UI you want to change though.

But let me introduce the [reStyle](https://addons.mozilla.org/en-US/firefox/addon/re-style/) add-on I am working on. It is a replacement for Stylish that takes care of writing UI styles to the correct userChrome / userContrent files for you (and does the usual user style manager stuff as well. It is not done yet, but I think it is already quite usable. I'd like to get some feedback on it!

> settings became complete invisible in the add-on manager (black on black, seemingly).

It's not even black on black. Inverting the Settings area turns it entirely blank, no matter the content. That's a Firefox bug.

I'll close this when I made the styles compatible with FF< 57 as well again and uploaded them on userstyles.org

**Comment by seascape** [comment]
Thanks for updating it!

In FF57 I currently use Stylus. If I understand, reStyle duplicates that functionality while also allowed modification of the two user*.css files?

Since FF57 I've assembled a rather extensive userChrome.css (45 rules or so); I would hope that reStyle would not erase/overwrite the current content unless directed to?

**Comment by NiklasGollenstede** [comment]
> In FF57 I currently use Stylus. If I understand, reStyle duplicates that functionality while also allowed modification of the two user*.css files?

Yepp. The UI isn't quite as sophisticated yet, but I was able to migrate all my user styles (UI + websites) to it.

> Since FF57 I've assembled a rather extensive userChrome.css (45 rules or so); I would hope that reStyle would not erase/overwrite the current content unless directed to?

Starting with version 0.2.0 id appends a managed section to those files, keeping the original content. But please not that the extension isn't well tested yet. You should defensively create  a backup of the files. If you encounter an bugs (or bad design) please tell me.

**Comment by NiklasGollenstede** [comment]
I have just updated the Firefox UI styles in this repo (again).
They are completely compatible with Firefox 64 (with dark default theme) and can be installed either with reStyle (which has also been updated quite a bit) or manually to the `userChrome`/`Content.css` files.
I see no reason to keep this open.
