### ISSUE TITLE
about-pages-dark needs updated for new about:privatebrowsing in Firefox 48

### ISSUE THREAD

**Issue by Caspy7** [NiklasGollenstede/stylish#3]
Firefox 48 (currently Developer Edition) comes with an updated about:privatebrowsing page which does not work properly with this style as it is.

**Comment by NiklasGollenstede** [comment]
Thanks for the heads up!
The commit above fixes the issue for now without changing anything in the current release version. I'll have a look at this again once the new FF 48 is released as stable
