### ISSUE TITLE
exclude about:reader

### ISSUE THREAD

**Issue by MacgyverJohnson** [NiklasGollenstede/stylish#4]
Hi MrNiklasGollenstede
Your About:reader dark usertyle is awesome but......
Any way to exclude about:reader in my global theme [https://userstyles.org/styles/31267/global-dark-style-changes-everything-to-dark](Global Dark style) so i can use your about:reader dark userstyle?
This userstyle has built in functionality of adding any type of exceptions including http|s ,ftp , file:/// , as well as about:pages
`/*----- SITES TO EXCLUDE -----*/
@-moz-document regexp("https?://(?!(en.wikipedia.org|github.com|www.youtube.com|www.facebook.com|userstyles.org|mail.google.com|www.reddit.com|www.google.com)).*"), url-prefix(ftp://), url-prefix(file://), url-prefix(about:*), url-prefix(javascript) { html, #newtab-window {background:` 

The thing is , as u can see i have added about:\* as an exception it does exclude about:addons(both page and on sidebars) about:memory..and others...but it doesnt exclude about:reader....any way around this?
for example go to this site [http://www.ghacks.net/2015/06/23/pro-and-con-of-mozillas-pocket-integration-in-firefox/](firefox Pocket) with global dark style enabled and your userstyle enabled....see its pitch black
![screen shot 2016-05-03 at 21 20 33](https://cloud.githubusercontent.com/assets/17729946/14988280/fed467b6-1174-11e6-9df7-6b176809821d.png)
without global dark style enabled its:
![screen shot 2016-05-03 at 21 22 05](https://cloud.githubusercontent.com/assets/17729946/14988333/2be16394-1175-11e6-8f79-7b7fe5f62d5c.png)

Any way to fix this......Thanks in advanced :) @NiklasGollenstede  @Cauterite

**Comment by MacgyverJohnson** [comment]
Update: Fixed it Huge thanks to Custom Stylish's tag feature which automatically disables/enables styles on certain pages http://choggi.org/wiki/stylish-custom/editdialog i have added 
this tag 
`"*|enable about:reader|disable"`
and now it works!!!

**Comment by NiklasGollenstede** [comment]
Hi,
interesting style. I started writing this so I'll just go ahead anyway:

here are several thoughts:
- the `@-moz-document` rules are linked with OR, so in you write `@-moz-document regexp("https?://(?!(exclude\\.this|and\\.this\\.too)).*"), url-prefix(about:) { ... }` then you are explicitly INcluding anything that starts with "about:".
- you should remember to always escape the '.' character in regular expressions
- url you want to exclude for about:reader is `about:reader?url=` encodeURIComponent({{ the actual site url }})

conclusion:
- something like this would work: `regexp("https?:\\/\\/(www\\.)?(?!(github\\.com|addons\\.mozilla\\.org)).*"), regexp("about:(?!reader).*")`
- obviously you would need to do the same with all other URL-shemes you want to include

**Comment by MacgyverJohnson** [comment]
thanks a lot
