### ISSUE TITLE
Discussion-Timeline Width Wrapping Content Underneath

### ISSUE THREAD

**Issue by asedarski** [NiklasGollenstede/stylish#5]
The Width calculation for The discussion-timeline class is causing the content to wrap as shown in the screenshot.

https://github.com/NiklasGollenstede/stylish/blob/master/github-custom-width.css#L31
I would recommend changing the width calculation to calc(100% - 220px)

![screenshot from 2016-09-02 13 26 58](https://cloud.githubusercontent.com/assets/15785161/18212391/02250b90-7111-11e6-9268-f890829c9626.png)

**Comment by NiklasGollenstede** [comment]
Yupp, that seems to fix it perfectly. Do you want to create a PR or should I just change that number myself?

**Comment by asedarski** [comment]
I'd be happy to put in a PR ☺️

**Comment by NiklasGollenstede** [comment]
I'm happy to wait for it then :)

**Comment by NiklasGollenstede** [comment]
Thanks, I have updated it on https://userstyles.org/styles/113930/github-custom-width too

**Comment by asedarski** [comment]
Awesome. Thanks for the opportunity to contribute!
