### ISSUE TITLE
about:settings and about:addons is broken (possibly others as well)

### ISSUE THREAD

**Issue by friendlyanon** [NiklasGollenstede/stylish#7]
https://forum.userstyles.org/discussion/52214/x

**Comment by friendlyanon** [comment]
Turns out it was just Classic Theme Restorer interfering. Sorry!

**Comment by NiklasGollenstede** [comment]
I was a bit surprised indeed.  As far as I know the about: pages don't change in the next versions ether.
But I think I still need to update that style a bit.
Thanks for you interest!
